name: Sync Playlist

on:
schedule:
- cron: '0 */6 * * *'
workflow_dispatch:

permissions:
contents: write

jobs:
sync:
runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Download Latest Playlist
    run: |
      curl -L "https://raw.githubusercontent.com/sm-monirulislam/Toffee-Auto-Update-Playlist/refs/heads/main/OTT_Navigator.m3u" -o One

  - name: Commit and Push Changes
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"
      git add One
      git commit -m "Auto Update Playlist" || exit 0
      git push
