name: Auto Sync One

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Latest M3U
        run: |
          curl -L "https://go.skym3u.top/qc98.m3u" -o One

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add One
          git commit -m "Auto update One file" || exit 0
          git push
